---
title: "Annotations"
author: "Chelsea Ursaner"
date: "4/18/2018"
output: html_document
---

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tidyr, lubridate, data.table, RSocrata, readxl)
```

###Expenses
```{r}
annotations <- read.csv("expense_annotations.csv")
dept_desc <- read_excel("~/R_labs/laBudget2/proposed_budget/data/FY18-19/QRY Department Description Text_1819Proposed.xlsx")

# Make new dataset to fit Socrata's annotation schema for departments
dept_desc <- dept_desc %>% select(-`Dept Number`) %>% rename(entity = `Dept Name`, text = `Budget Request Documentation Section Content`)
glimpse(dept_desc)
dept_desc$column <- "department_name"
write.csv(dept_desc, "dept_desc.csv", row.names=F)

# make new dataset for programs
# separate priority outcome line by splitting based on tab delimiter
prog_desc <- read.table("~/R_labs/laBudget2/proposed_budget/data/FY18-19/prog_desc.txt", sep = "\n", quote = "", strip.white = T, blank.lines.skip = T)

# remove all the lines with priority outcomes
prog_desc2 <- filter(prog_desc, !grepl("Priority Outcome",V1))

# do the rest in Excel to make sure it's all correct, but basically just removing blank cells
write.csv(prog_desc2, "prog_desc2.csv", row.names=F)
```

