---
title: "Other Budget Open Datasets"
author: "Chelsea Ursaner. Edited by Adam Scherling"
date: "6/11/2018"
output: word_document
---

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load required packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tidyr, lubridate, data.table, RSocrata, readxl)

# set directories
# data = directory where the data are saved
# login = directory where Socrata login information is saved
# (username.txt, password.txt)
dir <- list(data="~/github/laBudget/data/approved_budget/FY18-19/",
       login="~/github/laBudget/scripts/")

setwd(dir$data)

# get Socrata username and password for upload
username <- readLines(paste0(dir$login, 'username.txt'))
password <- readLines(paste0(dir$login, 'password.txt'))

# excel sheet filenames
excel_files <- list(
       gfrev="General Fund Revenue_1819Adopted.xlsx",
       positions="Positions_1819Adopted.xlsx",
       inc="Budget Requests Detail Sec2_1819Adopted.xlsx",
       pm="Performance Measures_1819Adopted.xlsx")
# excel_files <- list(
#        gfrev="General Fund Revenue_1819Proposed.xlsx",
#        positions="Positions_1819Proposed.xlsx",
#        inc="Budget Requests Detail_Sec2_1819Proposed.xlsx",
       # pm="Performance Measures_1819Proposed.xlsx")

# Socrata urls
urls <- list(
       gfrev='https://data.lacity.org/A-Prosperous-City/General-Fund-Revenue/qrkr-kfbh',
       positions='https://data.lacity.org/A-Well-Run-City/Positions/46qe-t7np',
       inc='https://data.lacity.org/A-Prosperous-City/General-City-Budget-Incremental-Changes/k4k6-bwwv',
       pm='https://data.lacity.org/A-Prosperous-City/Performance-Measures/bywz-284j'
       )

# Socrata endpoints
endpoints <- list(
       gfrev="https://data.lacity.org/resource/qrkr-kfbh.json",
       positions="https://data.lacity.org/resource/46qe-t7np.json",
       inc="https://data.lacity.org/resource/k4k6-bwwv.json",
       pm="https://data.lacity.org/resource/bywz-284j.json"
       )

# get a timestamp
timestamp <- gsub(':','.',now())
timestamp <- gsub(' ','_',timestamp)

# prevent R from writing to scientific notation
options(scipen=999)


```

### General fund revenue

```{r}
# Read the previous dataset from Socrata
gfrev_existing <- read.socrata(url = urls$gfrev)
write.csv(gfrev_existing, paste0('old_gfrev_',timestamp,'.csv'), row.names=F)
glimpse(gfrev_existing)
levels(as.factor(gfrev_existing$Fiscal.Year))

# take out proposed data for current year, if any exists
# gfrev_existing <- gfrev_existing %>% filter(Fiscal.Year != "2018_19_proposed")

# Read the new file
gfrev_current <- read_excel(paste0(dir$data, excel_files$gfrev))

# Standard removals and renaming
gfrev_current <- gfrev_current %>% 
       select (-`Org Level 5 Code`, -`Org Level 5 Name`) %>% 
       rename(Dept.Code = `Dept Code`,
              Department.Name = `Dept Name`,
              Program.Code = `Prog Code`,
              Program.Name = `Prog Name` ,
              Fund.Code = `Fund Code`,
              Fund.Name = `Fund Name`,
              Account.Code = `Account Code`,
              Account.Name = `Account Name`)
glimpse(gfrev_current)

# Specific edits for this year
gfrev_current <- gfrev_current %>% 
       select (-`2016-17 Actuals`,
              -`2017-18 Adopted Budget`,
              -`2017-18 Estimates`,
              -`2018-19 Proposed Budget`) %>% 
       rename(Revenue.Amount = `2018-19 Adopted Budget`)

# Filter out NAs, add fiscal year column
gfrev_current_clean <- filter(gfrev_current, Revenue.Amount != 0)
gfrev_current_clean$Fiscal.Year <- "2018_19_adopted"
glimpse(gfrev_current_clean)

# Make new dataset
gfrev_new <- rbind(gfrev_existing, gfrev_current_clean)
write.csv(gfrev_new, "gfrev_new.csv", row.names=F)

# names to match API endpoint
colnames(gfrev_new) <- c("dept_code","department_name","program_code",
       "program_name","fund_code","fund_name","account_code","account_name",
       "fiscal_year","revenue")

# Write table to Socrata using RSocrata package
write.socrata(dataframe = gfrev_new,
              dataset_json_endpoint = endpoints$gfrev,
              update_mode = "REPLACE",
              email = username,
              password = password)
```

### Postions
```{r}
# Read the previous dataset from Socrata
positions_existing <- read.socrata(url = urls$positions)
write.csv(positions_existing, paste0('old_positions_',timestamp,'.csv'), row.names=F)
glimpse(positions_current)
levels(as.factor(positions_existing$Budget))

# Read the new file
positions_current <- read_excel(paste0(dir$data, excel_files$positions))

# Standard removals and renaming
positions_current <- positions_current %>% 
       select(-`Org Level 5 Code`, -`Org Level 5 Name`) %>% 
       rename(Department.Code = `Dept Code`,
              Department.Name = `Dept Name`,
              Program.Code = `Prog Code`,
              Program.Name = `Prog Name` ,
              Fund.Code = `Fund Code`,
              Source.Fund.Code = `Source Fund Code`,
              Source.Fund.Name = `Source Fund Name`,
              Account.Code = `Account Code`,
              Account.Name = `Account Name`)

# Select only the data of interest
positions_current <- positions_current[,c(1:9, ncol(positions_current))]

# rename the latest data as "Positions"
colnames(positions_current)[ncol(positions_current)] <- "Positions"

# Filter out NAs, add fiscal year column
positions_current_clean <- filter(positions_current, Positions != 0)
positions_current_clean$Budget <- "2018-19 Adopted Budget"

# Check dataset
glimpse(positions_current_clean)

# Make new dataset
positions_new <- rbind(positions_existing, positions_current_clean)

write.csv(positions_new, "positions_new.csv", row.names=F)

# change column names to match API endpoint
colnames(positions_new) <- c("department_code","department_name","program_code",
       "program_name","fund_code","source_fund_code","source_fund_name",
       "account_code","account_name","budget","positions")

# Write table to Socrata using RSocrata package
write.socrata(dataframe = positions_new,
              dataset_json_endpoint = endpoints$positions,
              update_mode = "REPLACE",
              email = username,
              password = password)
```

### Incremental changes
```{r}
# Read the previous dataset from Socrata
inc_existing <- read.socrata(url = urls$inc)
write.csv(inc_existing, paste0('old_increments_',timestamp,'.csv'), row.names=F)
levels(as.factor(inc_existing$Budget))

# Read the new file
inc_current <- read_excel(paste0(dir$data, excel_files$inc))

# Standard removals and renaming
inc_current <- inc_current %>% 
       rename(Department.Code = `Department Code`,
              Department.Name = `Department Name`,
              Program.Code = `Program Code`,
              Program.Name = `Program Name` ,
              Fund.Code = `Fund Code`,
              Fund.Name = `Fund Name`,
              Source.Fund.Code = `Source Fund Code`,
              Source.Fund.Name = `Source Fund Name`,
              Budget.Request.Description = `Budget Request Description`,
              Budget.Request.Category = `Budget Request Category`,
              Account.Code = `Budget Object Code`,
              Account.Name = `Audit Budget Object Name`,
              One.Time..01....On.going..BB. = `One Time/ On-going`)

# select only the desired data
inc_current <- inc_current[,c(1:13, ncol(inc_current))]

# rename the incremental changes as "Incremental.Change"
colnames(inc_current)[ncol(inc_current)] <- "Incremental.Change"

# Filter out NAs, add fiscal year column
inc_current$Budget <- "2018-19 Adopted Budget Incremental Change from 2017-18 Adopted"

# Make new dataset
inc_new <- rbind(inc_existing, inc_current)

write.csv(inc_new, "inc_new.csv", row.names=F)

# change column names to match the API endpoint
colnames(inc_new) <- c("department_code","department_name","program_code",
       "program_name","fund_code","fund_name","source_fund_code",
       "source_fund_name","budget_request_description","budget_request_category",
       "account_code","account_name","one_time_ongoing")

# Write table to Socrata using RSocrata package
write.socrata(dataframe = inc_new,
              dataset_json_endpoint = endpoints$inc,
              update_mode = "REPLACE",
              email = username,
              password = password)
```

### Performance Measures
```{r}
# Read the previous dataset from Socrata
pm_existing <- read.socrata(url = urls$pm)
write.csv(pm_existing, paste0('old_pm_',timestamp,'.csv'), row.names=F)
levels(as.factor(pm_existing$Budget))
glimpse(pm_existing)

# Read the new file
pm_current <- read_excel(paste0(dir$data, excel_files$pm))

# Standard removals and renaming
pm_current <- pm_current %>% rename(Department.Code = `Dept Code`,
       Department.Name = `Department Name`,
       SubDept.Code = `Org Level 5 Code`,
       SubDept.Name = `Org Level 5 Name`,
       Program.Code = `Prog Code`,
       Program.Name = `Program Name` ,
       Performance.Measure.Code = `PM Code`,
       Performance.Measure.Name = `Performance Measure Name`,
       Unit = `Unit/Value`)

# select only the desired data
pm_current <- pm_current[,c(1:9, ncol(pm_current))]

# change the column name of the amount to "Performance.Measure.Amount"
colnames(pm_current)[ncol(pm_current)] <- "Performance.Measure.Amount"

# Filter out NAs, add fiscal year column
pm_current$Budget <- "2018-19 Adopted"

# Make new dataset
pm_new <- rbind(pm_existing, pm_current)

write.csv(pm_new, "pm_new.csv", row.names=F)

# change column names to match API endpoint
colnames(pm_new) <- c("department_code","department_name","subdept_code",
       "subdept_name","program_code","program_name","performance_measure_code",
       "performance_measure_name","unit","budget","performance_measure_amount")

# Write table to Socrata using RSocrata package
write.socrata(dataframe = pm_new,
              dataset_json_endpoint = endpoints$pm,
              update_mode = "REPLACE",
              email = username,
              password = password)
```

